### PR TITLE
Course Stats

### PR DESCRIPTION
**Pull request by gschorkopf**
Maybe someone can pick this up tomorrow?

#134 and #104

### CODE REVIEW

**Comment by gschorkopf** [comment]
screen shot 2015-02-05 at 7 43 30 pm

**Comment by gschorkopf** [comment]
@killpack @pdougall1 @canes6288 @ksenna

**Comment by killpack** [comment]
Birdies are good and bogeys are bad, right? Maybe we oughta make them green and red, respectively, and have par be a neutralish color?

**Comment by gschorkopf** [comment]
Great call!

**Pull request merged**
